# Generated by Django 2.2.7 on 2019-11-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=90)),
                ('fechainicio', models.DateField()),
                ('fechafinal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('equipo', models.CharField(max_length=90)),
                ('vehiculo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posicion', models.CharField(max_length=70)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Carrera')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Piloto')),
            ],
        ),
    ]
